# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: expressoh
  description: expression with fun and enthusiasm
  version: "1.0.0"
# the domain of the service
host: 0.0.0.0
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /expression:
    get:
      operationId: api.get_expression
      summary: expression values of a gene across samples
      description: |
        The expression endpoint returns all expression values of a specified gene across all samples of the dataset
      parameters:
        - name: symbol
          in: query
          description: symbol of gene of interest
          required: true
          type: string
      tags:
        - expression
      responses:
        200:
          description: An array of expression values
          schema:
            title: ArrayOfExpression
            type: array
            items:
              title: Expression
              type: object
              properties:
                celllinename:
                  type: string
                expression:
                  type: number